#   _____ _               _   _____ _                 _     _           _ _
#  /  __ \ |             | | /  ___| |               | |   (_)         (_) |
#  | /  \/ |__   ___  ___| |_\ `--.| |__   ___  _ __ | |    _ _ __ ___  _| |_ ___ _ __
#  | |   | '_ \ / _ \/ __| __|`--. \ '_ \ / _ \| '_ \| |   | | '_ ` _ \| | __/ _ \ '__|
#  | \__/\ | | |  __/\__ \ |_/\__/ / | | | (_) | |_) | |___| | | | | | | | ||  __/ |
#   \____/_| |_|\___||___/\__\____/|_| |_|\___/| .__/\_____/_|_| |_| |_|_|\__\___|_|
#                                              | |
#                                              |_|

# Plugin prefix!
Prefix: '&7[ &bChestShopLimiter &7]&f '

# Which lang file that you want to use, you can name it whatever you want to. Btw
# make sure To make one just copy and paste the whole lang.yml file and
# rename it, make sure you don't edit any of the config keys, by default it will make a EN_lang file if no lang file found
# WARNING it will throw an error and disabled the plugin if the <name>.yml file is not found!
Language: 'en_lang' # + yml

# Set this to true if you want to decrease the shopCreated value on player's data on ShopRemove. The refunded value will always be 1
RefundOnShopRemove: true
# Set this to true if you want to make a player that has unlimited shop permission to get a refund when he/she break the shop
# this can only be working if the RefundOnShopRemove is enabled!
RefundOnShopRemove-Unlimited: false

# This is all the dependency things for the plugin. If it enabled the plugin will try to hook to that plugin.
#
Dependency:
  PlaceholderAPI: true
  LuckPerms: true
  # For Essentials and CMI you can only enable 1. So choose it wisely. By default Essentials will be used (Recommended)
  Essentials: true
  CMI: false

# If this enabled, the plugin will collect some information about the server. If you don't want it to happens you can set this to 'false'
# it is recommended to not set it to false because it helps the dev to improve the plugin and know how much server using the plugin
use-bstats: true

# Title, the title setting for the plugin
# The fade-in, fade-out, and stay is on ticks format. Keep in mind that 1 second is 20 tick. So 1 second is 20 x 1 = 20, 2 second is 20 x 2 = 40, etc
Titles:
  MaxShopReached:
    enable: true
    title: '&aNotification'
    sub-title: '&fYou''ve reached the max shop amount!'
    fade-in: 20
    fade-out: 20
    stay: 40
    soundOnSend: 'NOTE_PLING'

# This is the sound of "success" and "failure" when using a command. Required to reload / restart the server if you made changes
# for the sound list, you can see it here https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# available config keys are volume, pitch, sound. The required key is only sound. Rest of them will be set to default
# if there's none found
# Example on sounds
# <key_name>:
#   sound: CLICK (Must)
#   volume: 1 (Optional)
#   pitch: 1 (Optional)
CommandSound:
  success:
    sound: CLICK
  failure:
    sound: ENTITY_BLAZE_DEATH

# This is the sounds for Inventories
# for the sound list you can see it here https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# available config keys are volume, pitch, sound. The required key is only sound. Rest of them will be set to default
# if there's none found
# Example on sounds
# <key_name>:
#   sound: CLICK (Must)
#   volume: 1 (Optional)
#   pitch: 1 (Optional)
InventorySound:
  MainMenu:
    click:
      sound: CLICK
    open:
      sound: CHEST_OPEN
    close:
      sound: CHEST_CLOSE
  PlayerSelector:
    click:
      sound: CLICK
    open:
      sound: CHEST_OPEN
    close:
      sound: CHEST_CLOSE
  Editor:
    click:
      sound: CLICK
    open:
      sound: CHEST_OPEN
    close:
      sound: CHEST_CLOSE


# This is the sounds for text editor
# for the sound list you can see it here https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# available config keys are volume, pitch, sound. The required key is only sound. Rest of them will be set to default
# if there's none found
# Example on sounds
# <key_name>:
#   sound: CLICK (Must)
#   volume: 1 (Optional)
#   pitch: 1 (Optional)
TextEditorSound:
  success:
    sound: CLICK
  failure:
    sound: ENTITY_BLAZE_DEATH

Debugging:
  # Allow logging to file?
  LogToFile: true
  # Log file format (No color code support)
  LogFormat: '[%date] [LOG] - [%logLevel] %message'

# Now'll explain you how the limit works. Sorry 4 my bad english
# Shop limit will be needed if the player that is checked didn't have the csl.limit.unlimited permission.
ShopLimit:
  # You can name it whatever you want to. The permission will be csl.limit.<name>
  # It is recommended to have the limit below 10, because it will create lags when the player join the server for the first time, when the plugin installed

  # Will not be used if force-default is set to false.
  default:
    limit: 5
  vip:
    limit: 10
  mvp:
    limit: 20
  # This will be needed to set to true if you want to make the player use the default limit if they don't have any permission for shop limit (csl.limit.<name>)
  force-default: true

# Will be used if you have Dependency.LuckPerms enabled!.
# WARNING PLEASE READ ALL OF THE COMMENT BELOW IF YOU WANT TO USE LuckPerms SUPPORT!
ShopLimitLuckPerms:
  # Please name it exactly the SAME name on the luckperms group! (Case sensitive!)
  # You can rename this, I use iron, gold, diamond because that is the group that I use for my test server
  # so you may ask how this thing work. Well its simple, it just check what group that the player is on. And then set the limit for it,
  # simple as that. You don't need other permission things for this
  # This is different from the default-value. This is basically a group that is generated automatically by LuckPerms. And what I know is
  # you cannot remove or rename this group
  default:
    limit: 5
  iron:
    limit: 10
  gold:
    limit: 20
  diamond:
    limit: 30
  # If the player's group didn't get specified above. Then the plugin will get this default value
  default-value:
    limit: 5

# The database setting for the plugin
Database:
  DatabaseType: 'FLAT_FILE'
  # Available type is 'SQL' 'MYSQL' 'FLAT_FILE'

  # For FLAT_FILE only
  FlatFile:
    # The save location for the database. Please only change this once. This will be ChestShopLimiter/database/<yaml_file_list>
    DatabaseFolder: "database"
  # For SQL Only
  SQL:
    # The type of this 'SQL' database. HIKARI_CP is really recommended!
    # Available type is : HIKARI_CP, SQL
    Type: HIKARI_CP
    # The database name. This will be playerData.db
    DatabaseName: 'playerData'
    # The save location for the database. Please only change this once. This will be ChestShopLimiter/database/playerData.db
    DatabaseFolder: 'database'
    # Force the data update even if there's no changes?. Will probably removed if there's no impact happening when updating the data
    ForceUpdate: false
  # For MySQL only
  MySQL:
    CompletelyAsync: true
    # Should all the task be ran on Async thread? (This will save performance, keep in mind that not every of the task is Async-able!)
    Type: HIKARI_CP
    # The type of this 'SQL' database. HIKARI_CP is really recommended!
    # Available type is : HIKARI_CP, SQL
    saveEvery: 300
    # Period save database in seconds
    host: "localhost"
    # The host / IP for the MySQL server
    port: 3306
    # The port for the server
    databaseName: "database"
    # The database name that will be created
    user: "root"
    # The username for the server
    password: ""
    # The password for the server