name: ChestShopLimiter
version: @version@
main: me.droreo002.cslimit.ChestShopLimiter
api-version: 1.13
depend: [ChestShop, OreoCore]
softdepend: [LuckPerms, Essentials, CMI]

commands:
  chestshoplimiter:
    aliases: [csl]
